---
title: "Update Data Dosen"
author: "Subbagian Registrasi dan Statistik Untirta"
date: "Diupdate pada: `r format(Sys.Date(), '%d %B %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
    theme: spacelab
    toc_float: no
  pdf_document:
    toc: yes
    toc_depth: '2'
---

```{=html}
<style type="text/css">

body{ /* Normal  */
      font-size: 14px;
  }
td {  /* Table  */
  font-size: 12px;
}
h1.title {
  font-size: 28px;
  color: Maroon;
}
h1 { /* Header 1 */
  font-size: 24px;
  color: Maroon;
  font-weight: bold;
}
h2 { /* Header 2 */
  font-size: 20px;
  color: Maroon;
  font-weight: bold;
}
h3 { /* Header 3 */
  font-size: 16px;
#  font-family: "Times New Roman", Times, serif;
  color: Maroon;
  font-weight: bold;
}
h4 { /* Header 4 */
  font-size: 14px;
  color: Maroon;
  font-weight: bold;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 12px;
}
</style>
```
<br>

Kepada Yth. <br>Staf Kepegawaian Fakultas <br>di lingkungan Universitas Sultan Ageng Tirtayasa

Kami dari Subbagian Registrasi dan Statistik secara rutin melakukan rekapitulasi tenaga Dosen baik yang berstatus PNS maupun non-PNS. Hal ini penting karena sering adanya permintaan data Dosen yang terkini dari beberapa pihak, misalnya dari BPS Kota, Kabupaten, atau Provinsi. Selain itu, setiap periode wisuda kami juga diminta data dosen terkini sebagai bahan pidato Rektor dan buku Album Wisuda. Berikut adalah rekapitulasi dosen PNS dan Dosen tetap Non PNS yang tercatat di Subbagian Registrasi dan Statistik.

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(readxl)
library(tidyverse)
library(janitor)
library(kableExtra)
list <- list.files("G:/My Drive/# REGISTRASI DAN STATISTIK/DATA PEGAWAI/DOSEN PNS/Update/")

pns <- NULL

for (i in 1:7) {
  pns <- rbind(pns, read_excel(paste0("G:/My Drive/# REGISTRASI DAN STATISTIK/DATA PEGAWAI/DOSEN PNS/Update/", list[i])))
}

data1 <- select(pns, Fakultas, JK) %>% group_by(Fakultas, JK) %>% summarize(n = n())
data1 <- pivot_wider(data1, names_from = JK, values_from = "n")
data1[is.na(data1)] <- 0
data1 <- adorn_totals(data1, where = c("col"), name = "JML")

list <- list.files("G:/My Drive/# REGISTRASI DAN STATISTIK/DATA PEGAWAI/DOSEN NON PNS/Update Data")

non <- NULL
for (i in 1:7) {
  non <- rbind(non, read_excel(paste0("G:/My Drive/# REGISTRASI DAN STATISTIK/DATA PEGAWAI/DOSEN NON PNS/Update Data/", list[i]), range = "A1:M100"))
}

# membuang semua baris yang kosong
non <- non %>% filter_all(any_vars(complete.cases(.)))

data2 <- select(non, Fakultas, JK) %>% group_by(Fakultas, JK) %>% summarize(n = n())
data2 <- pivot_wider(data2, names_from = JK, values_from = "n")
data2[is.na(data2)] <- 0
data2 <- adorn_totals(data2, where = c("col"), name = "JML")

data <- left_join(data1, data2, by = "Fakultas")
data$Total <- data$JML.x + data$JML.y
data <- adorn_totals(data, where = c("row"), name = "Total")
names(data) <- c("Fakultas", "L", "P", "JML", "L", "P", "JML", "Total")

kable(data) %>%
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  add_header_above(c(" " = 1, "Dosen PNS" = 3, "Dosen Non PNS" = 3, " " = 1))


jf_pns <- select(pns, Fakultas, JABATAN) %>% group_by(Fakultas, JABATAN) %>% summarize(n = n()) %>% pivot_wider(names_from = JABATAN, values_from = "n")

jf_pns <- select(jf_pns, Fakultas, GB, LK, L, AA, TP)

jf_pns[is.na(jf_pns)] <- 0

jf_pns <- adorn_totals(jf_pns, where = c("col"), name = "JML")


jf_non <- select(non, Fakultas, JFA) %>% group_by(Fakultas, JFA) %>% summarize(n = n()) %>% pivot_wider(names_from = JFA, values_from = "n")
jf_non <- select(jf_non, Fakultas, L, AA, TP)
jf_non[is.na(jf_non)] <- 0
jf_non <- adorn_totals(jf_non, where = "col", name = "JML")

jf <- left_join(jf_pns, jf_non, by = "Fakultas")
jf$Total <- jf$JML.x + jf$JML.y

fak <- data.frame(Fakultas = c("Hukum", "FKIP", "Teknik", "Pertanian","FEB", "FISIP", "Kedokteran"),
                  fak_order = c(1:7))

jf <- left_join(jf, fak, by = "Fakultas") %>% arrange(fak_order) %>% select(-fak_order)

jf <- adorn_totals(jf, where = "row", name = "Total")

names(jf) <- c("Fakultas", "GB", "LK", "L", "AA", "TP", "Jumlah", "L", "AA", "TP", "Jumlah", "Total")

kable(jf) %>%
  kable_styling(bootstrap_options = "striped", full_width = F) %>%
  add_header_above(c(" " = 1, "Dosen PNS" = 6, "Dosen Non PNS" = 4, " " = 1))

```

Oleh karena itu, kami memerlukan bantuan rekan-rekan Staf Kepegawaian Fakultas di lingkungan Universitasi Sultan Ageng Tirtayasa untuk membantu kami memperbaharui data dosen setiap ada perubahan. Adapun perubahan-perubahan data dosen yang diperlukan adalah sebagai berikut.

1.  **Dosen PNS**

    -   *Pendidikan Terakhir***.** Dosen-dosen dengan pendidikan terakhir S2 yang sedang melaksanakan tugas atau ijin belajar dan **sudah menjalani sidang promosi terbuka** bisa segera diubah status Pendidikan Terakhirnya menjadi S3.

    -   *Golongan*

    -   *Jabatan Akademik*

    -   *Fakultas* dan *Program Studi.* Keakuratan *homebase* dosen sangat diperlukan di dalam rekapitulasi untuk menghitung rasio dosen dan mahasiswa di setiap program studi.

    -   *Status Belajar.* Selama ini perhitungan rasio dosen dan mahasiswa tetap memperhitungkan dosen yang sedang tugas belajar, sehingga kurang menggambarkan rasio dosen dan mahasiswa yang sebenarnya. Oleh karena itu, kami akan membuat 3 status belajar.

        1.  **Aktif** bagi dosen yang tidak sedang tugas belajar atau ijin belajar
        2.  **Tugas** **Belajar** bagi dosen yang sedang melaksanakan tugas belajar
        3.  **Ijin** **Belajar** bagi dosen yang sedang melaksanakan ijin belajar <br><br>

    -   *Jenjang Studi* adalah jenjang studi lanjut yang sedang diambil oleh dosen tugas belajar atau ijin belajar.

    -   *Tahun Mulai Kuliah.* Tahun mulai kuliah bagi dosen yang sedang tugas belajar atau ijin belajar.

    -   *Keterangan.* Tempat kuliah bagi dosen yang sedang tugas belajar atau ijin belajar.

2.  **Dosen non PNS**

    -   *Pendidikan Terakhir*

    -   *Jabatan Akademik*

    -   *Fakultas* dan *Program Studi*

Dengan demikian, kami berharap agar rekan-rekan Staf Kepagawaian Fakultas bisa membantu kami setiap ada perubahan data-data di atas baik untuk dosen PNS maupun dosen non PNS. Rekan-rekan Staf Kepegawaian Fakultas bisa menghubungi kami melalui [**whatsapp**](wa.me/628111072357 "Whatsapp Riana Hadiana"){target="_blank"}, email ke registrasi\@untirta.ac.id atau bisa juga dengan mengedit langsung. Rekan-rekan bisa mengedit langsung melalui link di bawah ini sesuai dengan fakultas dan status dosen (PNS atau non PNS) yang akan diedit.

| No  | Fakultas   | Dosen PNS                                                                                                                                                          | Dosen non PNS                                                                                                                                                           |
|:----|:-----------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1\. | Hukum      | [**Edit**](https://docs.google.com/spreadsheets/d/1YbkkyE0UbYEqOefhCpcTt9IFPiOBZUg1/edit#gid=105639493 "Edit data dosen PNS Fakultas Hukum"){target="_blank"}      | [**Edit**](https://docs.google.com/spreadsheets/d/1XvVRw3UTeTVkYupwkgVjoJXflRjwVRJO/edit#gid=625457900 "Edit data dosen non PNS Fakultas Hukum"){target="_blank"}       |
| 2\. | FKIP       | [**Edit**](https://docs.google.com/spreadsheets/d/1Y_FSO4qlWRaSuKOfldoF4KBnejn1poiG/edit#gid=817148474 "Edit data dosen PNS FKIP"){target="_blank"}                | [**Edit**](https://docs.google.com/spreadsheets/d/1XvGN0y4gY1LYMe1I3wwFRNelBl0O-1tW/edit#gid=939326303 "Edit data dosen non PNS FKIP"){target="_blank"}                 |
| 3\. | Teknik     | [**Edit**](https://docs.google.com/spreadsheets/d/1YxbYOjvlOGPsEJ3383I25OnSkhpTG17Z/edit#gid=267147312 "Edit data dosen PNS Fakultas Teknik"){target="_blank"}     | [**Edit**](https://docs.google.com/spreadsheets/d/1YCNnwhTfzQ3PR-8jMfCCQqn9kzZt4VbS/edit#gid=794603767 "Edit data dosen non PNS Fakultas Teknik"){target="_blank"}      |
| 4\. | Pertanian  | [**Edit**](https://docs.google.com/spreadsheets/d/1YtLOlHudFJL44J2KMMrmMlOhQclHWhae/edit#gid=1002856352 "Edit data dosen PNS Fakultas Pertanian"){target="_blank"} | [**Edit**](https://docs.google.com/spreadsheets/d/1XzSJSR_hkppFsgkwlFZLxEBSx71pPUsm/edit#gid=1031155236 "Edit data dosen non PNS Fakultas Pertanian"){target="_blank"}  |
| 5\. | FEB        | [**Edit**](https://docs.google.com/spreadsheets/d/1YS75yTp16e_7WA284DUKwKQuy_peePqa/edit#gid=36297912 "Edit data dosen PNS FEB"){target="_blank"}                  | [**Edit**](https://docs.google.com/spreadsheets/d/1XqepU2EywMGydHDx1_VFNG6k_RXQr9X-/edit#gid=272608791 "Edit data dosen non PNS FEB"){target="_blank"}                  |
| 6\. | FISIP      | [**Edit**](https://docs.google.com/spreadsheets/d/1YZFG3rXxz-asob5Dca4Wi1M3hcgVVst_/edit#gid=1353640144 "Edit data dosen PNS FISIP"){target="_blank"}              | [**Edit**](https://docs.google.com/spreadsheets/d/1XtyjjcinJ8uGXT-NOk0BTeJotBNuc_RS/edit#gid=147078744 "Edit data dosen non PNS FISIP"){target="_blank"}                |
| 7\. | Kedokteran | [**Edit**](https://docs.google.com/spreadsheets/d/1YnzOQBUeGvSOE1eaM8i1t8v_ISADuga6/edit#gid=7040061 "Edit data dosen PNS Fakultas Kedokteran"){target="_blank"}   | [**Edit**](https://docs.google.com/spreadsheets/d/1XwOaa3bs3uND9jlKNLrDqa5yc3skJB07/edit#gid=1282921123 "Edit data dosen non PNS Fakultas Kedokteran"){target="_blank"} |
